# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import server_pb2 as server__pb2


class WorkerManagementStub(object):
    """Worker service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create = channel.unary_unary(
                '/server.WorkerManagement/create',
                request_serializer=server__pb2.NumberOfWorkers.SerializeToString,
                response_deserializer=server__pb2.Status.FromString,
                )
        self.list = channel.unary_unary(
                '/server.WorkerManagement/list',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=server__pb2.WorkerList.FromString,
                )
        self.delete = channel.unary_unary(
                '/server.WorkerManagement/delete',
                request_serializer=server__pb2.WorkerId.SerializeToString,
                response_deserializer=server__pb2.Status.FromString,
                )
        self.job = channel.unary_unary(
                '/server.WorkerManagement/job',
                request_serializer=server__pb2.WorkType.SerializeToString,
                response_deserializer=server__pb2.JobId.FromString,
                )


class WorkerManagementServicer(object):
    """Worker service
    """

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create': grpc.unary_unary_rpc_method_handler(
                    servicer.create,
                    request_deserializer=server__pb2.NumberOfWorkers.FromString,
                    response_serializer=server__pb2.Status.SerializeToString,
            ),
            'list': grpc.unary_unary_rpc_method_handler(
                    servicer.list,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=server__pb2.WorkerList.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=server__pb2.WorkerId.FromString,
                    response_serializer=server__pb2.Status.SerializeToString,
            ),
            'job': grpc.unary_unary_rpc_method_handler(
                    servicer.job,
                    request_deserializer=server__pb2.WorkType.FromString,
                    response_serializer=server__pb2.JobId.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server.WorkerManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkerManagement(object):
    """Worker service
    """

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.WorkerManagement/create',
            server__pb2.NumberOfWorkers.SerializeToString,
            server__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.WorkerManagement/list',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            server__pb2.WorkerList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.WorkerManagement/delete',
            server__pb2.WorkerId.SerializeToString,
            server__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.WorkerManagement/job',
            server__pb2.WorkType.SerializeToString,
            server__pb2.JobId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
